services:
  uptime-scope:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uptime-scope
    ports:
      - "8181:8181"
    restart: unless-stopped
    volumes:
      - ./checks.yaml:/app/checks.yaml:ro
